root: ./

structure:
  readme: README.md
  summary: SUMMARY.md

plugins:
  - theme-default
  - search
  - sharing
  - code
  - copy-code-button
  - expandable-chapters
  - page-toc
  - back-to-top-button

variables:
  version: "1.0"

